# Generated by Django 5.1.4 on 2025-03-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
